version: "2"

volumes:
  certs:
  data:
  config:


networks:
  teleport:


services:
  teleport:
    image: quay.io/gravitational/teleport:9.3.7
    container_name: teleport
    entrypoint: /bin/sh
    hostname: luna.teleport
    command: -c "/usr/bin/dumb-init teleport start -d -c /etc/teleport.d/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "443:443"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    networks:
      teleport:
        aliases:
          - proxy.luna.teleport

  bootstrap:
    image: quay.io/gravitational/teleport-lab:9
    container_name: teleport-bootstrap
    entrypoint: /bin/sh
    command: -c "/etc/teleport.d/scripts/generate-certs.sh"
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
      - certs:/mnt/shared/certs
    depends_on:
      - teleport
    networks:
      - teleport
